[package]
name = "commitlog_repro"
version = "0.1.0"
authors = ["Pi Lanningham <pi.lanningham@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
commitlog = "*"
